version: '3.8'

services:
  ghost:
    image: ghost:latest
    restart: always
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    environment:
      - url=http://localhost:2368
    ports:
      - "2368:2368"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost_password
    volumes:
      - ./mysql_data:/var/lib/mysql
